worker_processes ${{NUM_WORKERS}};
error_log stderr notice;
daemon off;
pid logs/nginx.pid;

env LAPIS_ENVIRONMENT;
env POSTGRES_HOST;
env POSTGRES_USER;
env POSTGRES_PASSWORD;
env POSTGRES_DB;
env POSTGRES_DB_TEST;

events {
  worker_connections 1024;
}

http {
  include mime.types;

  resolver 127.0.0.11 ipv6=off;

  lua_package_path './?.lua;./?/init.lua;;';
  lua_package_cpath './?.so;;';

  server {
    listen ${{PORT}};
    lua_code_cache ${{CODE_CACHE}};

    client_max_body_size 10m;
    client_body_buffer_size 256k;

    location / {
      default_type text/html;
      content_by_lua_block {
        require("lapis").serve("app")
      }
    }

    location /static/ {
      alias static/;
    }

    location /favicon.ico {
      alias static/favicon.ico;
    }
  }
}
